services:
  # Web Service
  - type: web
    name: pigfarm
    runtime: python
    plan: free
    region: oregon
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt && python fix_database.py && cd pigfarm && python manage.py collectstatic --no-input && python manage.py migrate --no-input && cd .. && python create_default_admin.py || echo 'Admin creation skipped'"
    startCommand: "cd pigfarm && gunicorn pigfarm.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: pigfarm-mrz6.onrender.com
      - key: DATABASE_URL
        sync: false
      - key: RENDER
        value: true
    autoDeploy: true
