# Generated by Django 5.1.6 on 2026-01-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='name',
            field=models.CharField(choices=[('farm_owner', 'Farm Owner/Admin'), ('farm_manager', 'Farm Manager'), ('farm_worker', 'Farm Worker'), ('feed_manager', 'Feed Manager'), ('accountant', 'Accountant/Finance'), ('viewer', 'Viewer/Inspector')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
    ]
