# Generated by Django 5.1.6 on 2025-03-19 18:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farm', '0010_alter_feedstock_cost_per_unit_alter_feedstock_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration_days', models.PositiveIntegerField(help_text='Number of days before the next vaccination is due')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('health_target_type', models.CharField(choices=[('sow', 'Sow'), ('piglet', 'Piglet')], max_length=10)),
                ('health_issue', models.CharField(help_text='Specify disease or health issue', max_length=255)),
                ('treatment_given', models.TextField(help_text='Describe treatment, medication, or deworming given')),
                ('dosage', models.CharField(blank=True, help_text='Dosage amount (e.g., 5ml)', max_length=50)),
                ('treatment_date', models.DateField(default=django.utils.timezone.now)),
                ('next_treatment_date', models.DateField(blank=True, help_text='Optional next treatment date', null=True)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('recovered', 'Recovered'), ('critical', 'Critical')], default='under_treatment', max_length=20)),
                ('piglet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='farm.piglet')),
                ('sow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='farm.sow')),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccination_target_type', models.CharField(choices=[('sow', 'Sow'), ('piglet', 'Piglet')], default='sow', max_length=10)),
                ('vaccination_date', models.DateField()),
                ('next_vaccination_date', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('vaccinated', 'Vaccinated'), ('overdue', 'Overdue'), ('pending', 'Pending')], default='pending', max_length=15)),
                ('piglet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.piglet')),
                ('sow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.sow')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.vaccination')),
            ],
        ),
        migrations.CreateModel(
            name='WeightRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('heart_girth', models.FloatField(help_text='Heart Girth in cm')),
                ('body_length', models.FloatField(help_text='Body Length in cm')),
                ('calculated_weight', models.FloatField(default=0.0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('sow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_records', to='farm.sow')),
            ],
        ),
    ]
