# Generated by Django 5.1.6 on 2025-03-20 12:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='status',
            field=models.CharField(choices=[('vaccinated', 'Vaccinated'), ('done', 'Done'), ('overdue', 'Overdue')], default='vaccinated', max_length=15),
        ),
    ]
