# Generated by Django 5.1.6 on 2025-03-21 09:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0010_alter_feedstock_cost_per_unit_alter_feedstock_name_and_more'),
        ('health', '0002_alter_vaccinationrecord_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weightrecord',
            name='recorded_at',
        ),
        migrations.AddField(
            model_name='weightrecord',
            name='piglet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.piglet'),
        ),
        migrations.AddField(
            model_name='weightrecord',
            name='recorded_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='status',
            field=models.CharField(choices=[('vaccinated', 'Vaccinated'), ('overdue', 'Overdue'), ('done', 'Done')], default='vaccinated', max_length=15),
        ),
        migrations.AlterField(
            model_name='weightrecord',
            name='body_length',
            field=models.DecimalField(decimal_places=2, help_text='Measure from head to tail in cm', max_digits=5),
        ),
        migrations.AlterField(
            model_name='weightrecord',
            name='calculated_weight',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=6),
        ),
        migrations.AlterField(
            model_name='weightrecord',
            name='heart_girth',
            field=models.DecimalField(decimal_places=2, help_text='Measure around the pig’s chest in cm', max_digits=5),
        ),
        migrations.AlterField(
            model_name='weightrecord',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='weightrecord',
            name='sow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.sow'),
        ),
    ]
