# Generated by Django 5.1.6 on 2025-03-23 17:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_remove_weightrecord_recorded_at_weightrecord_piglet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weightrecord',
            name='calculated_weight',
        ),
        migrations.AddField(
            model_name='weightrecord',
            name='difference',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=6),
        ),
        migrations.AddField(
            model_name='weightrecord',
            name='status',
            field=models.CharField(choices=[('increased', 'Increased'), ('decreased', 'Decreased'), ('no_change', 'No Change')], default='no_change', max_length=20),
        ),
        migrations.AddField(
            model_name='weightrecord',
            name='target_type',
            field=models.CharField(choices=[('sow', 'Sow'), ('piglet', 'Piglet')], default='sow', max_length=10),
        ),
        migrations.AddField(
            model_name='weightrecord',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Weight in kilograms', max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weightrecord',
            name='body_length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Body length in cm', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='weightrecord',
            name='heart_girth',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Heart girth in cm', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='weightrecord',
            name='recorded_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
