# Generated by Django 5.1.6 on 2025-04-19 19:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_remove_weightrecord_calculated_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cost of this health treatment', max_digits=10),
        ),
    ]
