# Generated by Django 5.1.6 on 2025-04-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_healthrecord_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='note',
            field=models.TextField(blank=True, help_text='Optional notes or observations about the health treatment', null=True),
        ),
    ]
