# Generated by Django 5.1.6 on 2025-04-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0006_healthrecord_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weightrecord',
            name='body_length',
        ),
        migrations.RemoveField(
            model_name='weightrecord',
            name='heart_girth',
        ),
        migrations.AlterField(
            model_name='weightrecord',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text='Measured weight in kilograms', max_digits=6),
        ),
    ]
