# Generated by Django 5.1.6 on 2025-02-27 20:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('capacity', models.PositiveIntegerField()),
                ('pig_count', models.PositiveIntegerField(default=0, editable=False)),
                ('status', models.CharField(choices=[('available', 'Available'), ('full', 'Full'), ('maintenance', 'Maintenance')], default='available', max_length=15)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('registered_date', models.DateField(default=django.utils.timezone.now)),
                ('birth_count', models.PositiveIntegerField(default=0)),
                ('total_piglets', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('young', 'Young Sow'), ('prime', 'Prime Sow'), ('old', 'Old Sow')], default='young', max_length=50)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sows', to='farm.room')),
            ],
        ),
        migrations.CreateModel(
            name='Piglet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('birth_date', models.DateField(default=django.utils.timezone.now)),
                ('initial_weight', models.FloatField()),
                ('current_weight', models.FloatField(default=0.0, editable=False)),
                ('sow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piglets', to='farm.sow')),
            ],
        ),
        migrations.CreateModel(
            name='BreedingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breeding_date', models.DateField()),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('sow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeding_records', to='farm.sow')),
            ],
        ),
    ]
