# Generated by Django 5.1.6 on 2025-02-28 14:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breedingrecord',
            old_name='delivery_date',
            new_name='heat_detection_date',
        ),
        migrations.AddField(
            model_name='breedingrecord',
            name='actual_farrow_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='breedingrecord',
            name='expected_farrow_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='breedingrecord',
            name='total_piglets_born',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='breedingrecord',
            name='breeding_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
