# Generated by Django 5.1.6 on 2025-02-28 14:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_rename_delivery_date_breedingrecord_heat_detection_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breedingrecord',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
