# Generated by Django 5.1.6 on 2025-03-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0004_remove_breedingrecord_actual_farrow_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='breedingrecord',
            name='actual_farrow_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='breedingrecord',
            name='breeding_date',
            field=models.DateField(blank=True, help_text='Must be within 3 days of heat detection', null=True),
        ),
        migrations.AlterField(
            model_name='breedingrecord',
            name='heat_detection_date',
            field=models.DateField(help_text='Date sow was first observed in heat'),
        ),
        migrations.AlterField(
            model_name='breedingrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('failed', 'Failed'), ('pregnant', 'Pregnant'), ('done', 'Done')], default='pending', max_length=10),
        ),
    ]
