# Generated by Django 5.1.6 on 2025-03-02 10:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0005_breedingrecord_actual_farrow_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breedingrecord',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
