# Generated by Django 5.1.6 on 2025-03-02 12:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0006_alter_breedingrecord_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the feed (e.g., Corn Meal, Pellets).', max_length=100, unique=True)),
                ('feed_type', models.CharField(choices=[('starter', 'Starter'), ('grower', 'Grower'), ('finisher', 'Finisher'), ('breeding', 'Breeding')], help_text='Type of feed.', max_length=20)),
                ('stock_quantity', models.FloatField(help_text='Total stock available (in kg or liters).')),
                ('unit', models.CharField(choices=[('kg', 'Kilograms'), ('liters', 'Liters'), ('bags', 'Bags')], default='kg', max_length=10)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, help_text='Cost per unit (e.g., per kg or per bag).', max_digits=10)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Total amount spent on this feed.', max_digits=12, null=True)),
                ('date_added', models.DateField(default=django.utils.timezone.now, help_text='Date the stock was added.')),
            ],
        ),
    ]
