# Generated by Django 5.1.6 on 2025-03-02 12:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0007_feedstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedstock',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='feedstock',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='feedstock',
            name='feed_type',
            field=models.CharField(choices=[('grain', 'Grain-Based'), ('pellet', 'Pellet Feed'), ('mash', 'Mash Feed'), ('supplement', 'Supplement')], max_length=50),
        ),
        migrations.AlterField(
            model_name='feedstock',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='feedstock',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='feedstock',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='feedstock',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('lb', 'Pounds')], max_length=20),
        ),
    ]
