# Generated by Django 5.1.6 on 2025-03-02 17:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0008_alter_feedstock_cost_per_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedstock',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='FeedingRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('feeding_target_type', models.CharField(choices=[('sow', 'Sow'), ('piglet', 'Piglet')], max_length=10)),
                ('quantity_used', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_records', to='farm.feedstock')),
                ('piglet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feeding_records', to='farm.piglet')),
                ('sow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feeding_records', to='farm.sow')),
            ],
        ),
    ]
