# Generated by Django 5.1.6 on 2025-03-17 14:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0009_alter_feedstock_name_feedingrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedstock',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='feedstock',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='feedstock',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
