# Generated by Django 5.1.6 on 2025-04-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0011_feedstock_initial_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='piglet',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='sow',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
    ]
