# Generated by Django 5.1.6 on 2025-04-22 06:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0012_piglet_status_sow_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='InactivePig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pig_type', models.CharField(choices=[('sow', 'Sow'), ('piglet', 'Piglet')], max_length=10)),
                ('original_id', models.UUIDField()),
                ('name', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('date_marked_inactive', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
