# Generated by Django 5.1.6 on 2025-04-22 11:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0013_inactivepig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insemination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the insemination method or material', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional details about the insemination')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='breedingrecord',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost of breeding process', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='breedingrecord',
            name='injection_1_date',
            field=models.DateField(blank=True, help_text='1st Inanga injection date', null=True),
        ),
        migrations.AddField(
            model_name='breedingrecord',
            name='injection_2_date',
            field=models.DateField(blank=True, help_text='2nd Inanga injection date', null=True),
        ),
        migrations.AddField(
            model_name='breedingrecord',
            name='injection_3_date',
            field=models.DateField(blank=True, help_text='3rd Inanga injection date', null=True),
        ),
    ]
