# Generated by Django 5.1.6 on 2025-04-22 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0014_insemination_breedingrecord_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='piglet',
            name='insemination_type',
            field=models.ForeignKey(blank=True, help_text='Insemination type used for this piglet', null=True, on_delete=django.db.models.deletion.SET_NULL, to='farm.insemination'),
        ),
    ]
