# Generated by Django 5.1.6 on 2025-04-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0015_piglet_insemination_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sow',
            name='origin',
            field=models.CharField(choices=[('sowed', 'Sowed'), ('birthed', 'Birthed'), ('born_in_farm', 'Born in Farm')], default='sowed', help_text='Where this sow came from (Sowed, Birthed, or Born in Farm)', max_length=20),
        ),
    ]
