# Generated by Django 5.1.6 on 2025-04-22 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0016_sow_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='sow',
            name='promoted_from_piglet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_sow', to='farm.piglet'),
        ),
    ]
