# Generated by Django 5.1.6 on 2025-04-23 16:30

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0018_remove_breedingrecord_breeding_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('source', models.CharField(choices=[('piglet_sale', 'Piglet Sale'), ('sow_sale', 'Sow Sale'), ('manure', 'Manure Sale'), ('service', 'Service Rendered'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
