# Generated by Django 5.1.6 on 2025-05-03 13:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0020_sow_inherited_insemination_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldPig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pig_type', models.CharField(choices=[('sow', 'Sow'), ('piglet', 'Piglet')], max_length=10)),
                ('sold_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_sold', models.DateField(default=django.utils.timezone.now)),
                ('piglet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farm.piglet')),
                ('sow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farm.sow')),
            ],
        ),
    ]
