# Generated by Django 5.1.6 on 2025-05-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0021_soldpig'),
    ]

    operations = [
        migrations.AddField(
            model_name='sow',
            name='initial_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost of buying the sow (if not born in the farm)', max_digits=10),
        ),
    ]
