# Generated by Django 5.1.6 on 2025-05-12 14:36

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0022_sow_initial_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('feed', 'Feed Purchase'), ('medicine', 'Veterinary Medicine'), ('maintenance', 'Maintenance'), ('salary', 'Staff Salary'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='incomerecord',
            name='source',
            field=models.CharField(choices=[('manure', 'Manure Sale'), ('service', 'Service Rendered'), ('other', 'Other')], max_length=50),
        ),
    ]
