# Generated by Django 5.1.6 on 2025-10-10 11:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0024_piglet_animal_tag_id_sow_animal_tag_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_name', models.CharField(help_text='Name of the bank account', max_length=200)),
                ('bank_name', models.CharField(help_text='Name of the bank', max_length=200)),
                ('account_number', models.CharField(help_text='Bank account number', max_length=100, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='Current account balance', max_digits=15)),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0, help_text='Starting balance when account was added', max_digits=15)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this account is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField(blank=True, help_text='Description of the transaction')),
                ('reference', models.CharField(blank=True, help_text='Transaction reference number', max_length=100)),
                ('transaction_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('balance_after', models.DecimalField(decimal_places=2, editable=False, help_text='Account balance after this transaction', max_digits=15)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='farm.bankaccount')),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
    ]
