# Generated by Django 5.1.6 on 2026-01-02 17:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0025_bankaccount_banktransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='piglet',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], help_text='Gender of the piglet', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='breedingrecord',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
