# Generated by Django 5.1.6 on 2026-01-02 17:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0026_piglet_gender_alter_breedingrecord_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PigTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pig_type', models.CharField(choices=[('sow', 'Sow'), ('piglet', 'Piglet')], max_length=10)),
                ('task_type', models.CharField(choices=[('vaccination', 'Vaccination'), ('weighing', 'Weighing'), ('diet_change', 'Diet Change'), ('breeding', 'Breeding/Insemination'), ('health_check', 'Health Check'), ('feeding_plan', 'Feeding Plan'), ('breastfeeding', 'Breastfeeding Monitoring'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Additional notes or instructions')),
                ('due_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('send_email', models.BooleanField(default=True, help_text='Send email reminder')),
                ('email_sent', models.BooleanField(default=False, editable=False)),
                ('reminder_days_before', models.PositiveIntegerField(default=2, help_text='Days before due date to send reminder')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('piglet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='farm.piglet')),
                ('sow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='farm.sow')),
            ],
            options={
                'ordering': ['due_date', '-created_at'],
            },
        ),
    ]
